# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sG1I7zHtR1R0lNvuEx7vJhV1t5MQ81tQ
"""

product_num = eval(input("Enter Number of products: "))    #task1
my_dict ={}
for x in range(product_num):
    productName = input("Enter Product Name: ")
    productPrice = int(input("Enter Product Price: "))
    my_dict[productName] = productPrice

while True:
    productName = input("Enter Product name: ")
    if productName in my_dict:
        print("The price  is: ", my_dict[productName])

    else:
        print("Not Found: ")
print(my_dict)

#task 2
dic ={'CAR': '100','Bike':'200','Truck':'300'}
print(dic)

x=eval(input("Enter Amount  in dollars: "))
for key ,values in dic.items():
  if int(values) < x:
    print(key,":",values)

#task 3
days = {'January':31, 'February':28, 'March':31, 'April':30,
        'May':31, 'June':30, 'July':31, 'August':31,
        'September':30, 'October':31, 'November':30, 'December':31}
name=input("Enter the name of a month: ")
for keys, values in days.items():
    if name == keys:
      print(values)
sort = {key:days[key] for key in sorted(days)}
print(sort.keys())
for keys, values in days.items():
  if int(values) == 31:
    print(keys,end=', ')

#task 4
sec={'Mani':"123",'basit':"321",'human':"456"}

def CheckUser_Pass(x,y):
    for keys ,values in sec.items():
        if keys == x  and y == sec[keys]:
            return ("you are succesfully logged in",keys,sec[keys])
        else:
            return  ("Please do check your login details")

x = input("Enter Username: ")    
y = input("Enter Your Password ")
print(CheckUser_Pass(x,y))

